name: DEV - CI

on:
  workflow_dispatch:

jobs:
  tests:
    name: Run Tests
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v3
      - name: Run Tests
        uses: ./.github/actions/test
        with:
          workingDirectory: api

  terraform:
    runs-on: ubuntu-latest
    environment: dev
    env:
      ARM_CLIENT_ID: ${{secrets.AZURE_CLIENT_ID}}
      ARM_CLIENT_SECRET: ${{secrets.AZURE_CLIENT_SECRET}}
      ARM_SUBSCRIPTION_ID: ${{secrets.AZUIRE_SUBSCRIPTION_ID}}
      ARM_TENANT_ID: ${{secrets.AZUIRE_TENANT_ID}}
      # TF_LOG: "TRACE"
      TF_VAR_resource_group_name: ${jobs.terraform.environment.name}-lol-scout-rg
      TF_VAR_storage_account_name: ${jobs.terraform.environment.name}lolscoutsa01

    steps:
      - uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform init
        run: terraform init |
          -backend-config="resource_group_name=$TF_VAR_resource_group_name"
          -backend-config="storage_account_name=$TF_VAR_storage_account_name"
          -backend-config="container-name=terraform-state"
          -backend-config="key=terraform.tfstate"
        working-directory: ./infrastructure
        # uses: hashicorp/terraform-github-actions@master
        # with:
        #   tf_actions_version: 0.12.13
        #   tf_actions_subcommand: 'init'
        #   tf_actions_working_dir: './infrastructure'
        #   tf_actions_comment: false
        # env:
        #   TF_VAR_environment: env

      # - name: Terraform Format
      #   run: terraform fmt -check
      #   working-directory: ./infrastructure

      - name: Terraform Plan
        run: terraform fmt -check
        working-directory: ./infrastructure
        # uses: hashicorp/terraform-github-actions@master
        # with:
        #   tf_actions_version: 0.12.13
        #   tf_actions_subcommand: 'plan'
        #   tf_actions_working_dir: './infrastructure'
        #   tf_actions_comment: false
        # env:
        #   TF_VAR_environment: env

      - name: Call terraform output
        run: |
          output=$(terraform output env)
          echo $output

      # - name: Terraform Apply
      #   run: terraform apply -auto-approve
      #   working-directory: ./infrastructure
