name: TEST - CI

on:
  push:
    branches:
      - main

jobs:
  tests:
    name: Run Tests
    runs-on: ubuntu-latest
    environment: test
    steps:
      - uses: actions/checkout@v3
      - name: Run Tests
        uses: ./.github/actions/test
        with:
          workingDirectory: api